# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev2-hello-world',
                'doc_host': 'https://fmussari.github.io',
                'git_url': 'https://github.com/fmussari/nbdev2-hello-world',
                'lib_path': 'nbdev2_hello_world'},
  'syms': { 'nbdev2_hello_world.core': { 'nbdev2_hello_world.core.foo': ( 'https://fmussari.github.io/core.html#foo',
                                                                          'https://github.com/fmussari/nbdev2-hello-world/blob/master/nbdev2_hello_world/core.py#L7')}}}